### ISSUE TITLE
'/usr/local/bin/python3' ERROR

### ISSUE THREAD

**Issue by Chertoganov** [samanfrm/ADRtarget#1]
How to solve this error? 

FileNotFoundError: [WinError 3] The system cannot find the path specified: '/usr/local/bin/python3'

it happened after this command 
virtualenv -p /usr/local/bin/python3 py3 #creates virtual environment py3 using python v3.7

**Comment by samanfrm** [comment]
You need to define the python path based on your absolute directory from the root. If you are working with Windows you might need to define the path properly based on your system.
