### ISSUE TITLE
openFDA request error

### ISSUE THREAD

**Issue by ChloeJKim** [samanfrm/ADRtarget#2]
Hi @samanfrm, 

Thank you so much for pushing your code! very impressed with your work. 

While I was trying to replicate the work, I encountered request error from openFDA. 

I followed **python openFDAapi.py 0 2134 [openFDA api key] [local path]** this command (using the API key) but got this error. As an alternative, I also queried smaller chunks of compounds but still an erro. Can you please take a look to see what I need to do to fix this issue? 

![image](https://user-images.githubusercontent.com/52466133/99472689-04119f00-28fe-11eb-85f5-24828f367547.png)

Thank you so much in advance!

**Comment by samanfrm** [comment]
Dear Chloe,

Thank you for using our code. I see the error is related to your
certificate verification. You need to use a valid and registered API key.
Note that FDA provides different types of key with particular query limit
per day! We used an unlimited key without any limits to access updated FDA
records with no query limit. You can request OpenFDA to get a verified key.

Thanks

**Comment by ChloeJKim** [comment]
I see! I'll request the unlimited key and try again. Thanks for helping @samanfrm
