### ISSUE TITLE
data preprocessing

### ISSUE THREAD

**Issue by ChloeJKim** [samanfrm/ADRtarget#3]
Hi @samanfrm 

This is Chloe again. 
While I was looking at V1_compounds_FDA.csv data

I see these data between numbers (pic below)

![image](https://user-images.githubusercontent.com/52466133/99576403-c9a41280-298e-11eb-9fe0-b3f1cb15a449.png)

do I need to get rid of these rows before running openFDAoutput2modelformat.py?
It seems these data cause problem while running the script. 

also do you mind providing these csv output files as well?

data/v1_compounds_FDA_model_format_SOC_ocr_prob.csv
data/v1_compounds_FDA_model_format_SOC_ocr_bool.csv
data/v1_compounds_FDA_model_format_HLGT_ocr_prob.csv
data/v1_compounds_FDA_model_format_HLGT_ocr_bool.csv

Thanks a lot!

**Comment by samanfrm** [comment]
You should open it in Python using typical Pandas package, then you would
be fine. Excel doesn't handle huge character-specific delimited files.

**Comment by ChloeJKim** [comment]
I got it working when I used read_csv instead! 

One thing I wanted to clarify is the input data that goes into the random forest model. 

README mentions that input files are **The 2 files provided, baseMatrix and v1_compounds_FDA_model_format_*_ocr_bool.csv, where * is either SOC or HLGT, are the inputs for the R script.**

Does this mean I can either put: in the RF model?
1) data/v1_compounds_FDA_model_format_SOC_ocr_prob.csv & data/v1_compounds_FDA_model_format_HLGT_ocr_prob.csv 
2) data/v1_compounds_FDA_model_format_SOC_ocr_bool.csv &
data/v1_compounds_FDA_model_format_HLGT_ocr_bool.csv
OR
all of these four into the model? Because I saw that all four files were used from the script like this: 
![image](https://user-images.githubusercontent.com/52466133/99756319-b897f600-2aa1-11eb-957b-e8fa913dbc38.png)

Thank you in advance @samanfrm I look forward to your reply

**Comment by SedaArat** [comment]
Hi Chloe,

Yes, the README is correct: "README mentions that input files are *The 2
files provided, baseMatrix and
v1_compounds_FDA_model_format_*_ocr_bool.csv, where * is either SOC or
HLGT, are the inputs for the R script." *

You need the *baseMatrix.Rdata* as the baseMatrix input file and
**_bool.csv* as the adr input file. The code will not work if you use
*_prob.csv files instead of *_bool.csv .

Hope it helps,
Seda

**Comment by ChloeJKim** [comment]
Thank you! @SedaArat using those files I tried out the R_modeling code to get Features_ADRs_predictions.csv. However, I cannot seem to get this output csv file, I went through the same script you provided and set my working directory to where this R code, SOC/ and HLGT/folders are: **setwd ("/Users/kimc26/Desktop/ADRtarget/data")**
I have included the code here: 

[test.txt](https://github.com/samanfrm/ADRtarget/files/5585944/test.txt)

**R script** is in : Users/kimc26/Desktop/ADRtarget/data
**v1_compounds_FDA_model_format_SOC_ocr_bool** is in:  Users/kimc26/Desktop/ADRtarget/data/SOC
**baseMatrix** is in Users/kimc26/Desktop/ADRtarget/data/SOC

Do you know what's wrong? and what I need to fix to get features_adr_predictions csv file?

**Comment by ChloeJKim** [comment]
so when I run the functions it gives me error with + signs & I'm not sure what I should fix
![image](https://user-images.githubusercontent.com/52466133/100026246-4b38dd80-2d9f-11eb-8c2b-971a5928b922.png)

**Comment by SedaArat** [comment]
Hi Chloe,

The test.txt file only includes the functions that are needed for the other
functions. And the + signs you sent is not shown properly.

Can you send me how you ran the codes and what the error message is?

Seda

**Comment by ChloeJKim** [comment]
Hi @SedaArat,
This is what I ran, I got up to **get.rf.model (path4res = "/Users/kimc26/Desktop/ADRtarget/data")** to try out the model in R_code_modeling.R but get this error: 

![image](https://user-images.githubusercontent.com/52466133/100035446-0e76e180-2db3-11eb-83c1-4fd9a6f298a1.png)

[R_sample.txt](https://github.com/samanfrm/ADRtarget/files/5586842/R_sample.txt)

**Comment by ChloeJKim** [comment]
I think the error is mainly coming from this line in the script:  **my.mldr = mldr_from_dataframe (as.data.frame (cbind (bm.training, ADR.tr.disc)), 
                                 labelIndices = ADR.label.indeces)** in **get.rf.model** function because dimension of bm.training is (0, 413) & (1328,27) for ADR.tr which I think might be the reason why? 

Is there a way to solve this error message?

**Comment by SedaArat** [comment]
The issue is bm_tr.Rdata file cannot be found in the directory. Did you
generate it earlier? Where is your file bm_tr.Rdata located?

**Comment by ChloeJKim** [comment]
bm_tr.Rdata is saved in **"/Users/kimc26/Desktop/ADRtarget/data/SOC"** and I have reflected this change within the getrfmodel function like this: **bm.training <- readRDS ("SOC/bm_tr.Rdata")** & **ADR.tr.disc <- readRDS ("SOC/adr_tr.Rdata")**

when I execute the code line by line, it breaks at line 66

![image](https://user-images.githubusercontent.com/52466133/100122684-86ceb880-2e2e-11eb-962f-f227059fc7fd.png)

**Comment by ChloeJKim** [comment]
I would also really appreciate if you could provide **HLGT/SOC_ADR_target_assoc_final.csv** files as I cannot run the script right now but would like to see the results.

**Comment by SedaArat** [comment]
When you run dim (bm.training), it returns 0 rows and 413 columns. For some
reason, the code is not run properly in your system and so cbind is not
working. Please run the code step by step and check if they are read and
stored properly in your R environment. Maybe all you need to do set your
working directory to " */Users/kimc26/Desktop/ADRtarget/data/" . *

**Comment by ChloeJKim** [comment]
Thank you @SedaArat I was able to reproduce the results by fixing parts of the code. 
& came along with another Q, What do you mean by **"for all models except in SOC"**

![image](https://user-images.githubusercontent.com/52466133/100149521-2f8f0f00-2e53-11eb-8f31-cab66f91aa81.png)

Because when I first ran with **v1_compounds_FDA_model_format_SOC_ocr_bool.csv** my **summ_metrics_ADRs.csv** looks different than what you provided in the data folder. 

Below is the pic of my summ_metrics_ADRs.csv ran with v1_compounds_FDA_model_format_SOC_ocr_bool.csv

![image](https://user-images.githubusercontent.com/52466133/100149803-990f1d80-2e53-11eb-8608-93ed081074fc.png)

**Comment by SedaArat** [comment]
that means the summ_metrics_ADRs.csv will not be generated if you are
running the SOC-level analysis. Dont worry - it was not used in our paper.

**Comment by ChloeJKim** [comment]
so I ran RF model with HLGT data & for summ_metrics_ADRs.csv got this: which doesn't seem to show adverse events under ADR column.

![image](https://user-images.githubusercontent.com/52466133/100274029-9f180380-2f12-11eb-8a19-8298328a2c7d.png)

But when I see summ_metrics_ADRs.csv (provided in the data folder), this included adverse events.

![image](https://user-images.githubusercontent.com/52466133/100274171-d71f4680-2f12-11eb-9ae6-1371807ee80e.png)

The code below seems to put numbers for ADR column in the res.table.
![image](https://user-images.githubusercontent.com/52466133/100274527-6d536c80-2f13-11eb-895c-a3c81e893363.png)

To replicate your work, did you just paste the adverse events in another column manually? 

Thank you so much for helping out! @SedaArat
