### ISSUE TITLE
question on ADR_target.ipynb 

### ISSUE THREAD

**Issue by ChloeJKim** [samanfrm/ADRtarget#4]
Hello this is Chloe, 

Hope you had a good Thanksgiving. 
I came across a question regarding the data that goes in ADR_target.ipynb 
For step:  Determine associations for each replicate run individually

![image](https://user-images.githubusercontent.com/52466133/100687282-d92f3e00-3334-11eb-9d82-cb66a6d140ad.png)

I'm hold up on this part: 
Q) where/how would I get the "features_ADRs_predictions.csv file for i == 0? 
I have Features_ADRs_predictions.csv for different seed from RF model (R_modeling script) but what should I put or where should I get the features_ADRs_predictions.csv for i == 0? 

Thank you for helping :)

**Comment by ri23** [comment]
If you have 5 different seeds (below 1,2,3,4 or 5) used in the R_modelling script, with results in 5 diffseed folders, then you can just adjust the code to: 
```
diff_SEEDS = [1,2,3,4,5]
N_reps = 5

for i in range(N_reps):
     seed=diff_SEEDS[i]
     path='~/ADRtarget/data/'+level+'_diffSeed_'+str(seed)+'/'
```

**Comment by ri23** [comment]
further down in the code you encounter another two of those `if i==0:` statements. Please adjust the code there in the same manner

**Comment by ri23** [comment]
The only reason we had our code as in the notebook is because one of our folders did not have a seed specified in their folder name.

**Comment by ChloeJKim** [comment]
thank you @ri23 for clarifying, after getting rid of `if i==0:` I was able to go through the code. I'm at the last part (filter out non-significant associations)

when I run this cell, I ran into following error where p value already exist. Do you see anything that I need to fix here? this is the exact code provided and I've not changed anything. 
![image](https://user-images.githubusercontent.com/52466133/100693312-742e1500-3341-11eb-9d0f-af0f5eccd911.png)

![image](https://user-images.githubusercontent.com/52466133/100693270-5eb8eb00-3341-11eb-8025-76b0d5bc45cc.png)

**Comment by ri23** [comment]
Hi Chloe,

Can you try to rerun the previous two cells where ATM is initiated before
running this particular cell? I suspect it is just a problem that one
cannot run this particular cell twice because the pval column gets inserted
in ATM, so running it a second time gives this error.

**Comment by ChloeJKim** [comment]
@ri23 I just tried and got the file 

Is this how it supposed to look like for HLGT_ADR_target_assoc_final.csv?
![image](https://user-images.githubusercontent.com/52466133/100694544-2bc42680-3344-11eb-9e3d-81cd9878107c.png)

**Comment by ri23** [comment]
Yes, that looks good to me.
